### ISSUE TITLE
t_string! raises an ERROR

### ISSUE THREAD

**Issue by obioma** [Baptistemontan/leptos_i18n#100]
Hi,

when testing the t_string! functionality  with an enhanced examples/csr/src/app.rs

```rust
let inc = move |_| set_counter.update(|count| *count += 1);
    
    let count = move || counter.get();
    
    assert_eq!(t_string!(i18n, click_count, count ),"You clicked 0 times");     // New, to test t_string!
    
    view! {
        <p>{t!(i18n, click_count, count)}</p>
        // <p>{t!(i18n, click_count, count = move || counter.get())}</p>
        <button on:click=inc>{t!(i18n, click_to_inc)}</button>

```

 I did experience  the following issue (Note: feature "interpolate_display" has beenenabled in Cargo.toml) :

```shell
error[E0599]: no method named `var_count_string` found for struct `click_count_builder` in the current scope
  --> src/app.rs:34:45
   |
34 |     assert_eq!(t_string!(i18n, click_count, count ),"You clicked 0 times");
   |                                             ^^^^^
   |
  ::: src/main.rs:4:1
   |
4  | leptos_i18n::load_locales!();
   | ---------------------------- method `var_count_string` not found for this struct
   |
help: there is a method `var_count` with a similar name
   |
34 |     assert_eq!(t_string!(i18n, click_count, var_count ),"You clicked 0 times");
   |                                             ~~~~~~~~~

For more information about this error, try `rustc --explain E0599`.
error: could not compile `csr` (bin "csr") due to 1 previous error
2024-05-14T12:09:57.122064Z ERROR ❌ error
```
Any suggestion what I'm doing wrong. Here my toolchain, I'm using most actual i18n version 

```shell
active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.78.0 (9b00956e5 2024-04-29)
```

Thank you in advance
BR

**Comment by Baptistemontan** [comment]
Thanks for the issue, just checked the code and it's because those functions are not created when using the `debug_interpolations` feature, it's a mistake on my part, I'm fixing the issue and I'll create a patch

**Comment by obioma** [comment]
> Thanks for the issue, just checked the code and it's because those functions are not created when using the `debug_interpolations` feature, it's a mistake on my part, I'm fixing the issue and I'll create a patch

Hi,
thx. Any suggestion where I can find the patch?
Best

**Comment by Baptistemontan** [comment]
I'm sorry for the wait, I've been dealing with personal issues and haven't got time to work on it, I'll notify you when it's done.

**Comment by obioma** [comment]
If you give me a hint where I would try for myself.
