### ISSUE TITLE
`tracing` feature enable

### ISSUE THREAD

**Issue by tetuaoro** [Baptistemontan/leptos_i18n#101]
I have enabled `tracing` feature on `leptos` crate `version = 0.6`. I use `leptos_i18n::load_locales!();` to load locales json file. I got this error when compiling :

```bash
error[E0433]: failed to resolve: use of undeclared crate or module `tracing`
  --> src/lib.rs:14:1
   |
14 | leptos_i18n::load_locales!();
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `tracing`
   |
   = note: this error originates in the attribute macro `::leptos::leptos_dom::tracing::instrument` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I need to use `tracing`. Thanks for your help.

### Config

- Linux 22.04.1-Ubuntu
- cargo 1.78
- cargo-leptos 0.2.17
- ~~leptos nightly~~

**Comment by tetuaoro** [comment]
After looking at the `Cargo.toml` file, I forgot to enable `tracing` in the hydrate feature. My bad.

**Comment by Baptistemontan** [comment]
I'm sorry I did'nt saw this issue as it was closed fast, this crates use tracing for now, there is no tracing annotations generated or used anywhere, so it must comes from other generated code like leptos. If you want tracing used within this crate feel free to open an issue and PR are always welcome !
