### ISSUE TITLE
Date and number formatting

### ISSUE THREAD

**Issue by Baptistemontan** [Baptistemontan/leptos_i18n#115]
For now everything is displayed with their `leptos::IntoView` implementation, this is fine for strings or actual views, but this crate should add support for formatting dates and numbers.

I'm open to any suggestions of crates that would help with this. 
I know JS `Intl` object is great for that but this is not usable on the server.
A crate using `unic_langid` for language identifier would be great.

There is `icu4x` that looks great, proposed in #89

**Comment by VincentBerthier** [comment]
For dates chrono has an unstable feature "unstable-locales" that can do it.
For numbers, you can look at [num-format](https://docs.rs/num-format/latest/num_format/)

**Comment by Baptistemontan** [comment]
Thanks @VincentBerthier for the proposal, I'll look into it when I will work on formatting!

**Comment by Baptistemontan** [comment]
Not sure if I'll work on this for v0.4, there is still some work to do for 0.4 and I want to push a release soon as it's been a while since the last one, I'm getting back on the project after a long period and don't want to drag v0.4 for too long

**Comment by Baptistemontan** [comment]
@VincentBerthier I went with `icu4x` because it proposed formatting for dates, time and lists too, plus the addition of a real plural backend
