### ISSUE TITLE
Implement EnumIter for Locale

### ISSUE THREAD

**Issue by fabianboesiger** [Baptistemontan/leptos_i18n#142]
It would be great to have something like [`strum::EnumIter`](https://docs.rs/strum/latest/strum/derive.EnumIter.html) implemented on the `Locale` enum. This would make it much easier to implement something like a language select button without hardcoding all the possible locales. Instead, we could simply iterate through the available locales.

**Comment by Baptistemontan** [comment]
Hello, there is already the [`get_all`](https://docs.rs/leptos_i18n/latest/leptos_i18n/trait.Locale.html#tymethod.get_all) method implemented for the `Locale` enum, I fail too see what `EnumIter` would bring that this method does'nt allow, could you elaborate ?

**Comment by fabianboesiger** [comment]
That's exactly what I was looking for. In that case, implementing EnumIter is indeed unnecessary.
Thank you!
