### ISSUE TITLE
100% memory consume

### ISSUE THREAD

**Issue by tetuaoro** [Baptistemontan/leptos_i18n#150]
Hi, Ive just upgraded from leptos v`0.6` to v`0.7-gamma3` (rc0). The `0.5.0-gamma2` version of `leptos_i18n` consumes all the memory and 66 % of the swap memory due to the parent process `collect2` and the child process `ld` *(comes from gcc)*. My app didn't compile at the end and sometimes my laptop restarted because of the lack of memory.

I know it's because of this crate because I've been debugging for 3 days by disabling each crates, one by one, and today the culprit revealed itself.

### Environment
- Ubuntu amd64 noble `24.04`
- cargo & rustup stable `1.82.0`
- gcc (Ubuntu 13.2.0-23ubuntu4) `13.2.0`

Cargo.toml
```toml
leptos = { version = "0.7.0-gamma3" }
axum = { version = "0.7", optional = true }
...
leptos_i18n = { version = "0.5.0-gamma2", default-features = false, features = [
    "yaml_files",
    "track_locale_files",
    "interpolate_display",
] }
```

I did not find how to solve this issue. I tried to manually compile with `cargo build ... --jobs=1` and also increase swap memory by 2x without success.

EDIT

### Change

Change I made :

```rust
- let title = t!(i18n, aepa.meta_title);
+ let title = move || t_string!(i18n, aepa.meta_title);
...
view! {
   <Title text=title/>
   ....
}
```

Generally, it's just from `t!(...)` to `move || t_string!(...)`.

### Error output

```bash
error: linking with `cc` failed: exit status: 1

= note: LC_ALL="C" PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib.......
...
  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
```

**Comment by Baptistemontan** [comment]
Could you share the project this happens with ? Without a way to reproduce it I can't do much, I may have vagues ideas were this could come from (macros.) but without a way to debug and test the fixes I don't know how I can fix that

**Comment by tetuaoro** [comment]
> Could you share the project this happens with ?
Sure, I made a reproduction here https://github.com/tetuaoro/i18n-reproduction.git.
You can checkout to the 2 tags `step0.4` and `step0.5`.

**Comment by tetuaoro** [comment]
This reproduction compiles as expected, but the memory consumption increases further by 10x - 300MB for v`0.4` and 32GB for `0.5`.

**Comment by Baptistemontan** [comment]
thanks for the reproduction! I'll take a look asap

**Comment by Baptistemontan** [comment]
I've been trying everything to reproduce this issue, and I'm unable to see any consequent differences beetween the two tags, sure v0.5 more ressources but did not went near as high as you...

**Comment by tetuaoro** [comment]
Really 😱 ?? waouh...I don't know why I'm the only one with that. Ok, thank you for the reply. I'll investigate more.

**Comment by tetuaoro** [comment]
Really 😱 ?? waouh...I don't know why I'm the only one with that. Ok, thank you for the reply. I'll investigate more.
