### ISSUE TITLE
Issues with `t_string` macro

### ISSUE THREAD

**Issue by Baptistemontan** [Baptistemontan/leptos_i18n#152]
### Discussed in https://github.com/Baptistemontan/leptos_i18n/discussions/151

<div type='discussions-op-text'>

<sup>Originally posted by **fabianboesiger** October 28, 2024</sup>
Hello there!

I'm trying to use `t_string!(i18n, key)`but I'm getting the following compile time error:

```
no method named `build_string` found for struct `DisplayBuilder` in the current scope
method `build_string` is available on `&str`
```

I can't seem to figure out what I'm missing, maybe a feature? The version I'm using is:

```
leptos_i18n = { version = "0.4.1", features = ["interpolate_display", "track_locale_files"] }
```

Thanks for any help!</div>

**Comment by fabianboesiger** [comment]
Thank you, everything works perfectly now!
