### ISSUE TITLE
Setting meta tags on dynamic load

### ISSUE THREAD

**Issue by sabify** [Baptistemontan/leptos_i18n#168]
How is it possible to set meta tags while dynamic load is enabled?

Something like the following:

```rust
let i18n = use_i18n();
provide_meta_context();
view! {
    <Title text=t_string!(i18n, app_name) />
    <Meta name="Description" content=t_string!(i18n, app_description) />
}
```

**Comment by Baptistemontan** [comment]
I'm not at home and can't test your code, so can you elaborate on your issue? What is the problem here? And what is the expected behavior ?

**Comment by sabify** [comment]
Sure and thanks for your prompt attention.

Without using `dynamic_load` feature for `leptos_i18n`, the above code works as it is intended for, but when you enable the `dynamic_load` feature, `t_string!` macro returns future. Based on you documentation, we may need to use `AsyncDerived` to be able to use `*_string`/`*_display` and I try it with `Suspense`/`Suspend` and I still wasn't able to make the code work.

**Comment by Baptistemontan** [comment]
can you try this:
```rust
let i18n = use_i18n();
let title_text = AsyncDerived:new(move || t_string!(i18n, app_name));

<Title text=|| title_text.get().unwrap_or_default() />
```

**Comment by sabify** [comment]
It works! Thanks for taking your time.

It may worth document the usage.

Please fill free to close this issue.

**Comment by Baptistemontan** [comment]
Yes I can probably add this as an exemple in the book, thanks for the feedback!
