### ISSUE TITLE
Could not found configuration file (i18n.json) : No such file or directory (os error 2)

### ISSUE THREAD

**Issue by dessalines** [Baptistemontan/leptos_i18n#44]
This happens anywhere I try to run `leptos_i18n::load_locales!();`

version `0.1.3`

**Comment by dessalines** [comment]
I switched to using the git url in my `Cargo.toml`, and that fixed the issue.

**Comment by Baptistemontan** [comment]
If you are saying that the git url works it means you want to use v0.2, you can use "0.2.0-beta" for the crates.io version

**Comment by dessalines** [comment]
Sweet, thanks!
