### ISSUE TITLE
Feature request: component with defaultValue and extract translations out of it

### ISSUE THREAD

**Issue by beckend** [Baptistemontan/leptos_i18n#56]
here is an example:

```typescript
<Trans
  i18nKey="myKey" // optional -> fallbacks to defaults if not provided
  defaults="hello <italic>beautiful</italic> <bold>{{what}}</bold>" // optional defaultValue
  values={{ what: 'world'}}
  components={{ italic: <i />, bold: <strong /> }}
/>
```
Source: https://react.i18next.com/latest/trans-component

They extract the keys and the defaults value then writes to for example en.json, no need to edit that huge file after a while.

They also supply a function `t` where you can invoke for example `t('my-key', { defaultValue: 'hello {{name}}', values: 'me' }`, this is necessary since you might want to get a translation string outside a view component.

The whole point is to automatically extract translations with minimal effort avoiding the need to open, read and edit huge translation files.

**Comment by Baptistemontan** [comment]
Can I have an exemple (no need for code, just an explanation) for when a default has an advantage? 
From my perspective there is only 2 situations where the default can appear:
- The current locale don't exist
- The current locale exist but the key don't exist in that locale

The way `load_locales!` work makes it impossible to fall into the first situation, and you can fall into the second one but the macro will emit a warning that there is a missing key, and will automatically default to the value of the default locale (see #45).

**Comment by beckend** [comment]
Let it be super stupid, which makes it good:
Panic if the defaultValue is detected more than once when the key already has a defaultValue, it's very easy in codebases to search for the i18n key and the cause is apparent.

**Comment by beckend** [comment]
This then becomes a matter of translating the key once anywhere, and the {en,fr...}.json is self maintained.

**Comment by Baptistemontan** [comment]
> Panic if the defaultValue is detected more than once when the key already has a defaultValue, it's very easy in codebases to search for the i18n key and the cause is apparent.

I'm sorry but don't understand what you mean by that

**Comment by Baptistemontan** [comment]
The current locale can't not exist, or Rust has a compiler bug, because the supported locales are represented as an enum that is matched against.

For 1. when you say "write {locale}.json" do you mean modify the file ?
And for 2. it is already what's happening

**Comment by beckend** [comment]
So with this change, it's going to be different, because it needs to scan the codebase for the translations, and write all translations first, this means the macro will actually error until you flush everything to disk/memory and then it has to reevaluate.

**Comment by Baptistemontan** [comment]
Ok so if I understand correctly what you would want is to write like `t!(..., default = "whatever string")` and the macro would write the default to the locales files if the key don't exist ?

**Comment by beckend** [comment]
Yes precisely, panic if default is detected more than once, after everything flushed to disk/memory then the macro will understand

**Comment by beckend** [comment]
I would be good if it also warned if a key is present but not being used, the source of truth should be the codebase

**Comment by Baptistemontan** [comment]
> the source of truth should be the codebase

While I agree that there should be a warning if a key is not used, I don't agree the codebase should be the source of truth, the translations should reflect what the locales files provides, not the other way around.

And I refuse to make a macro that create/modify files, macros are already abitrary code run not even sandboxed, being able to read whatever files is already too much in my opinion, any step beyond that is malware. 

And even if I was okay with this, this would mean a complete rework of the crate, with a completly different philosophy in mind. It'll be better creating a new library focusing with this goal.

**Comment by beckend** [comment]
Anyway thanks for the discussion.

**Comment by Baptistemontan** [comment]
The alternative would be something like what [`rust-i18`](https://github.com/longbridgeapp/rust-i18n#extractor) is doing, they have a separate CLI to extract translations. What you are asking is not a job for macros, it would be like asking `sqlx` to create/ modify tables/schemas if a query fail, but it's a job that can be automated, it just need another tool for that.
