### ISSUE TITLE
Integration with icu4x?

### ISSUE THREAD

**Issue by Boscop** [Baptistemontan/leptos_i18n#89]
Btw, there is prior art in the form of [i18next](https://i18next.com), [fluent-rs](https://crates.io/crates/fluent) and now icu4x: https://github.com/projectfluent/fluent-rs/issues/329
It probably makes sense to integrate [icu4x](https://crates.io/crates/icu) into `leptos_i18n` or take inspiration from it, regarding how it handles the intricacies of languages.

**Comment by Baptistemontan** [comment]
I've been looking for a way to handle localisation for date/number/ect... and icu4x looks like a good fit, I'll look into it and how to integrate the features it propose, thanks for the suggestion
