### ISSUE TITLE
Recompile on changed locale files

### ISSUE THREAD

**Issue by alilee** [Baptistemontan/leptos_i18n#90]
Is there a way to get `cargo leptos watch` to recompile the lib (`load_locales!`) when files in the locales directory change?

I tried `watch-additional-files = ["locales"]` in `Cargo.toml` but cargo doesn't think that anything in the lib has changed so just links.

**Comment by Baptistemontan** [comment]
Yes this is a known issue: #86, and I don't have a solution yet to this problem.
