### ISSUE TITLE
Leptos warning ' .. outside reactive context ... ' when running

### ISSUE THREAD

**Issue by obioma** [Baptistemontan/leptos_i18n#94]
Hi,

thx for the crate, it works pretty fine.

During the execution (I use V0.3.0-rc) I get in the console the following warning from Leptos

```
At /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_i18n-0.3.0-rc/src/context.rs:18:16, you access a signal or memo (defined at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_i18n-0.3.0-rc/src/context.rs:67:18) outside a reactive tracking context. This might mean your app is not responding to changes in signal values in the way you expect.

Here’s how to fix it:

1. If this is inside a `view!` macro, make sure you are passing a function, not a value.
  ❌ NO  <p>{x.get() * 2}</p>
  ✅ YES <p>{move || x.get() * 2}</p>

2. If it’s in the body of a component, try wrapping this access in a closure: 
  ❌ NO  let y = x.get() * 2
  ✅ YES let y = move || x.get() * 2.

3. If you’re *trying* to access the value without tracking, use `.get_untracked()` or `.with_untracked()` instead.
```
You maybe find some time to take a look at it, I tried with exchanging 

```rust
#[inline]
pub fn get_locale(self) -> T {
    self.0.get()
}
```
with 
```rust
#[inline]
pub fn get_locale(self) -> T {
    (move || self.0.get())()
}
```
Which was not succesful.

**Comment by Baptistemontan** [comment]
Hello, could you show the code where you call `get_locale` ? This method is meant to be called inside the Leptos reactive system like the warnings state, I can help you resolve that problem if you explain what you want to archieve. Do you want code that can react to the change of the locale? Or do you want to access the locale in a non reactive way ?

**Comment by obioma** [comment]
Hi,
code is in the body of app.rs, basically on the top of the tree. I use it to log the actual locale.  Will remove it.
```rust
#[component]
pub fn QApp() -> impl IntoView {
    let i18n = provide_i18n_context();
    let act_locale = i18n.get_locale();
    log!("Locale: {:#?}", act_locale);
```
Nevertheless it would be great to understand how to fix it, doing the fixes ii the warning didn't help.
Thx

**Comment by Baptistemontan** [comment]
There is multiple way you can fix this, but what I would suggest you is to use [`create_effect`](https://docs.rs/leptos/latest/leptos/fn.create_effect.html) and do this:
```rust
#[component]
pub fn QApp() -> impl IntoView {
    let i18n = provide_i18n_context();
    create_effect(|_| {
        let act_locale = i18n.get_locale();
        log!("Locale: {:#?}", act_locale);
    });
```
This will subscribe to the changes of the locale and log it every time the locale change

**Comment by obioma** [comment]
Does the trick, thx a lot.
